=== ismaelom83/aplicacion-amor/practicas/ud5xpath/XPATH04/xpath_04.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="actividades">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="actividad" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="codigo"/>
              <xs:element type="xs:string" name="titulo"/>
              <xs:element type="xs:date" name="fecha_inicio"/>
              <xs:element name="sesiones">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:byte" name="minutos_sesion"/>
                    <xs:element type="xs:byte" name="sesiones_semana"/>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="intensidad" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="nivel" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ismaelom83/aplicacion-amor/practicas/ud6xslt/xslt04/XPath_04.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="xpath_04.xsl"?>
<!DOCTYPE actividades [
<!ELEMENT actividades (actividad+)>
<!ELEMENT actividad (codigo, titulo, fecha_inicio, sesiones)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT fecha_inicio (#PCDATA)>
<!ELEMENT sesiones (minutos_sesion, sesiones_semana)>
<!ELEMENT minutos_sesion (#PCDATA)>
<!ELEMENT sesiones_semana (#PCDATA)>
<!ATTLIST actividad nivel CDATA #REQUIRED>
<!ATTLIST sesiones intensidad CDATA #REQUIRED>
]>
<actividades xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation= "xpath_04.xsd">
	<actividad nivel="infantil">
		<codigo>A01</codigo>
		<titulo>Al agua patos</titulo>
		<fecha_inicio>2017-01-15</fecha_inicio>
		<sesiones intensidad="suave"> 	
			<minutos_sesion>45</minutos_sesion>
			<sesiones_semana>3</sesiones_semana>
		</sesiones>
	</actividad>

	<actividad nivel="adultos">
		<codigo>A02</codigo>
		<titulo>Spinning y agua</titulo>
		<fecha_inicio>2017-01-08</fecha_inicio>
		<sesiones intensidad="fuerte"> 			
			<minutos_sesion>45</minutos_sesion>
			<sesiones_semana>3</sesiones_semana>
		</sesiones>
	</actividad>
	<actividad nivel="adultos">
		<codigo>A03</codigo>
		<titulo>Spinning en el agua</titulo>
		<fecha_inicio>2017-01-15</fecha_inicio>
		<sesiones intensidad="moderada"> 			
			<minutos_sesion>60</minutos_sesion>
			<sesiones_semana>2</sesiones_semana>
		</sesiones>
	</actividad>
	<actividad nivel="infantil">
		<codigo>A04</codigo>
		<titulo>Socorrismo</titulo>
		<fecha_inicio>2017-01-15</fecha_inicio>
		<sesiones intensidad="moderada"> 			
			<minutos_sesion>45</minutos_sesion>
			<sesiones_semana>2</sesiones_semana>
		</sesiones>
	</actividad>
	<actividad nivel="infantil">
		<codigo>A05</codigo>
		<titulo>Perfeccionamiento en el agua</titulo>
		<fecha_inicio>2017-01-15</fecha_inicio>
		<sesiones intensidad="moderada"> 			
			<minutos_sesion>45</minutos_sesion>
			<sesiones_semana>2</sesiones_semana>
		</sesiones>
	</actividad>
	<actividad nivel="adultos">
		<codigo>A06</codigo>
		<titulo>Aprender a nadar</titulo>
		<fecha_inicio>2017-02-15</fecha_inicio>
		<sesiones intensidad="suave"> 			
			<minutos_sesion>30</minutos_sesion>
			<sesiones_semana>2</sesiones_semana>
		</sesiones>
	</actividad>
</actividades>
