=== ismaelom83/aplicacion-amor/practicas/ud2xml/xml01_1/xml01_1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="mundo">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="pais" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="nombre"/>
              <xs:element type="xs:string" name="capital"/>
              <xs:element  name="continente">
			  <xs:simpleType>
			  <xs:restriction base="xs:string">
			  <xs:pattern value="Asia|America|Europa"></xs:pattern>
			  
			  <!-- <xs:enumeration value="Asia"></xs:enumeration> -->
			   <!-- <xs:enumeration value="America"></xs:enumeration> -->
			    <!-- <xs:enumeration value="Europa"></xs:enumeration> -->
				
			  </xs:restriction>
			  </xs:simpleType>
			  </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ismaelom83/aplicacion-amor/practicas/ud2xml/xml01_1/xml01_1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE mundo [ 
<!ELEMENT mundo (pais+)>
<!ELEMENT pais (nombre, capital, continente)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT capital (#PCDATA)>
<!ELEMENT continente (#PCDATA)>
<!ATTLIST mundo xmls:xsi CDATA #IMPLIED>
<!ATTLIST  mundo xsi:noNamespaceSchemaLocation CDATA  #IMPLIED >
 ]>
<mundo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation= "xml01_1.xsd">
	<pais>
		<nombre>Alemania</nombre>
		<capital>berlin</capital>
		<continente>Europa</continente>
	</pais>

	<pais >
		<nombre>Argentina</nombre>
		<capital>buenos aires</capital>
		<continente>America</continente>
	</pais>

	<pais>

		<nombre>Bahamas</nombre>
		<capital>Nassau</capital>
		<continente>America</continente>
	</pais>

	<pais>
		<nombre>Afganistan</nombre>
		<capital>Kabul</capital>
		<continente>Asia</continente>
	</pais>

	<pais>
		<nombre>Arabia Sudita</nombre>
		<capital>Riad</capital>
		<continente>Asia</continente>

	</pais>
</mundo>
