=== ismaelom83/aplicacion-amor/practicas/ud5xpath/XPATH03/xpath_03.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="peliculas">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="pelicula"  maxOccurs="unbounded" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element type="xs:string" name="nombre"/>
						<xs:element name="valoracion">
						<xs:complexType>
						<xs:simpleContent>
						<xs:extension base="xs:string">
						<xs:attribute type="xs:byte" name="puntos" use="optional"/>
						</xs:extension>
						</xs:simpleContent>
						</xs:complexType>
						</xs:element>
						<xs:element type="xs:string" name="publico"/>
					</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ismaelom83/aplicacion-amor/practicas/ud5xpath/XPATH03/XPath_03.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE peliculas [
<!ELEMENT peliculas (pelicula+)>
<!ELEMENT pelicula (nombre, valoracion, publico)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT valoracion (#PCDATA)>
<!ELEMENT publico (#PCDATA)>
<!ATTLIST valoracion  puntos CDATA #REQUIRED>
]>
<peliculas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation= "xpath_03.xsd">
	<pelicula>
		<nombre>La invenci&#243;n de Hugo</nombre>
		<valoracion puntos="7"/>
		<publico>Todos los p&#250;blicos</publico>
	</pelicula>
	<pelicula>
		<nombre>La piel que habito</nombre>
		<valoracion puntos="4"/>
		<publico>Adultos</publico>
	</pelicula>
	<pelicula>
		<nombre>Los descencientes</nombre>
		<valoracion puntos="6"/>
		<publico>Mayores de 12</publico>
	</pelicula>
</peliculas>
