=== ismaelom83/aplicacion-amor/practicas/ud5xpath/XPATH01/xpath_01.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="edificio">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="vivienda" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:byte" name="piso"/>
              <xs:element type="xs:string" name="puerta"/>
              <xs:element name="vecinos">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="nombre" maxOccurs="unbounded" minOccurs="0"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ismaelom83/aplicacion-amor/practicas/ud5xpath/XPATH01/XPath_01.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE  edificio[
<!ELEMENT  edificio (vivienda+)>
<!ELEMENT  vivienda (piso, puerta, vecinos)>
<!ELEMENT  piso (#PCDATA)>
<!ELEMENT  puerta (#PCDATA)>
<!ELEMENT  vecinos (nombre+)>
<!ELEMENT   nombre (#PCDATA)>
]>
<edificio  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation= "xpath_01.xsd">
	<vivienda>
		<piso>1</piso>
		<puerta>A</puerta>
		<vecinos>
			<nombre>David</nombre>
			<nombre>Sara</nombre>
		</vecinos>
	</vivienda>
	<vivienda>
		<piso>1</piso>
		<puerta>B</puerta>
		<vecinos>
			<nombre>Jaime</nombre>
			<nombre>Luis</nombre>
		</vecinos>
	</vivienda>
</edificio>
