=== ismaelom83/aplicacion-amor/practicas/ud2xml/xml05/xml05.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="company">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="empleado">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="nombre"/>
              <xs:element type="xs:string" name="apellido"/>
              <xs:element type="xs:int" name="contacto"/>
              <xs:element type="xs:string" name="email"/>
              <xs:element name="direccion">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="ciudad"/>
                    <xs:element type="xs:string" name="estado"/>
                    <xs:element type="xs:int" name="zip"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ismaelom83/aplicacion-amor/practicas/ud2xml/xml05/xml05.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE company [ 
<!ELEMENT company (empleado+)>
<!ELEMENT empleado (nombre, apellido, contacto, email, direccion)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT contacto (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT direccion (ciudad, estado, zip)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT estado (#PCDATA)>
<!ELEMENT zip (#PCDATA)>
 ]>
<company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation= "xml05.xsd">
    <empleado>
        <nombre>Juan</nombre>
        <apellido>Snchez</apellido>
        <contacto>123456789</contacto>
        <email>Juansanchez@comoany.com</email>
        <direccion>
            <ciudad>Bangalore</ciudad>
            <estado>Kamataka</estado>
            <zip>560212</zip>
        </direccion>
    </empleado>
</company>
